# Generated by Django 2.1.7 on 2019-04-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='kennedy hall', max_length=30),
            preserve_default=False,
        ),
    ]
