# Generated by Django 2.1.7 on 2019-04-29 04:32

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/data/jisungpark1.jpg', upload_to=event.models.user_directory_path),
        ),
    ]
