# Generated by Django 2.1.7 on 2019-04-29 04:36

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(default='data/jisungpark1.jpg', upload_to=event.models.user_directory_path),
        ),
    ]
