# Generated by Django 2.1.7 on 2019-05-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190429_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(default='data/jisungpark1.jpg', upload_to='images/'),
        ),
    ]
