# Generated by Django 2.1.7 on 2019-05-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190503_2229'),
        ('event', '0005_auto_20190501_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='authentication.SparkUser'),
        ),
    ]
