# Generated by Django 2.1.7 on 2019-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkuser',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
