# Generated by Django 2.1.7 on 2019-05-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_sparkuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkuser',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparkuser',
            name='gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparkuser',
            name='image',
            field=models.ImageField(default='data/jisungpark1.jpg', upload_to='images/'),
        ),
    ]
