# Generated by Django 2.1.7 on 2019-05-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_sparkuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkuser',
            name='interest',
            field=models.CharField(default='No interest', max_length=150),
        ),
        migrations.AlterField(
            model_name='sparkuser',
            name='email',
            field=models.CharField(default='No Emails', max_length=100),
        ),
    ]
